import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState, useEffect } from 'react';

const RecipeTop: NextPage = () => {
  const [recipes, setRecipes] = useState([]);

  const init = async () => {
    const res = await fetch('http://127.0.0.1:8000/api/recipe');
    console.log('res', res);
    const json = await res.json();
    // console.log('json', json);
    // console.log('json.recipes', json.recipes);
    const recipes = json.recipes.data;
    // console.log('recipes', recipes);
    setRecipes(recipes);
  };

  useEffect(() => {
    init();
  }, []);

  return (

    <Head>
    <title>Create Next App < /title>
      < meta name = "description" content = "Generated by create next app" />
        <link rel="icon" href = "/favicon.ico" />
          </Head>

          < div className = { styles.container } >
            <main className = { styles.main } >
              <h1 className={ styles.title }>
                レシピ一覧
  </h1>
  {
    recipes.map((recipe, index) => (
      <div key= { index } >
      { recipe.id }
            { recipe.user_id }
            { recipe.title }
            { recipe.description }
            { recipe.image }
            { recipe.cost }
            { recipe.created_at }

      < /div>
    ))
  }
  </main>

    < footer className = { styles.footer } >
      <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  target = "_blank"
  rel = "noopener noreferrer"
    >
    Powered by{ ' ' }
  <span className={ styles.logo }>
    <Image src="/vercel.svg" alt = "Vercel Logo" width = { 72} height = { 16} />
      </span>
      < /a>
      < /footer>
      < /div>
      < />
  );
}

export default RecipeTop;